# Welcome to Jekyll!
#

# Site settings
title: KAI startup studio
description: |
  digital experience consulting for brands and startups
owner: kai # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: contact@kaistud.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kaistud.io" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/sguyon/kai
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:contact@kaistud.io
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  # weibo: http://www.weibo.com/u/sachag
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  # weixin: xxx
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
